// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

// Defines values for DuckRequestSize.
const (
	DuckRequestSizeLarge  DuckRequestSize = "large"
	DuckRequestSizeMedium DuckRequestSize = "medium"
	DuckRequestSizeSmall  DuckRequestSize = "small"
)

// Valid indicates whether the value is a known member of the DuckRequestSize enum.
func (e DuckRequestSize) Valid() bool {
	switch e {
	case DuckRequestSizeLarge:
		return true
	case DuckRequestSizeMedium:
		return true
	case DuckRequestSizeSmall:
		return true
	default:
		return false
	}
}

// Defines values for RubberDuckSize.
const (
	RubberDuckSizeLarge  RubberDuckSize = "large"
	RubberDuckSizeMedium RubberDuckSize = "medium"
	RubberDuckSizeSmall  RubberDuckSize = "small"
)

// Valid indicates whether the value is a known member of the RubberDuckSize enum.
func (e RubberDuckSize) Valid() bool {
	switch e {
	case RubberDuckSizeLarge:
		return true
	case RubberDuckSizeMedium:
		return true
	case RubberDuckSizeSmall:
		return true
	default:
		return false
	}
}

// DuckRequest defines model for DuckRequest.
type DuckRequest struct {
	Color string          `json:"color"`
	Name  string          `json:"name"`
	Size  DuckRequestSize `json:"size"`
}

// DuckRequestSize defines model for DuckRequest.Size.
type DuckRequestSize string

// DucksResponse defines model for DucksResponse.
type DucksResponse struct {
	Ducks []RubberDuck `json:"ducks"`
}

// Error defines model for Error.
type Error struct {
	// Code Example: 400
	Code int `json:"code"`

	// Message Example: Invalid request.
	Message string `json:"message"`
}

// RubberDuck defines model for RubberDuck.
type RubberDuck struct {
	// Color Example: yellow
	Color string `json:"color"`

	// ID Example: 1
	ID int `json:"id"`

	// Name Example: Classic Yellow
	Name string `json:"name"`

	// Size Example: medium
	Size RubberDuckSize `json:"size"`
}

// RubberDuckSize Example: medium
type RubberDuckSize string

// CreateDuckJSONRequestBody defines body for CreateDuck for application/json ContentType.
type CreateDuckJSONRequestBody = DuckRequest
